apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - secrets.yaml
  - frontend.yaml
  - urls-service.yaml
  - iam-service.yaml
  - ingress.yaml

images:
  - name: ghcr.io/artemborodinevgenyevich/urls-frontend
    newTag: latest
  - name: ghcr.io/artemborodinevgenyevich/urls-service
    newTag: latest
  - name: ghcr.io/artemborodinevgenyevich/iam-service
    newTag: latest
  - name: ghcr.io/artemborodinevgenyevich/urls-migration
    newTag: latest
  - name: ghcr.io/artemborodinevgenyevich/iam-migration
    newTag: latest
