apiVersion: v1
kind: Secret
metadata:
  name: urls-service-secrets
  namespace: urls
type: Opaque
stringData:
  POSTGRES_PASSWORD: "pswd"
  REDIS_PASSWORD: "pswd"
---
apiVersion: v1
kind: Secret
metadata:
  name: iam-service-secrets
  namespace: urls
type: Opaque
stringData:
  POSTGRES_PASSWORD: "pswd"
  REDIS_PASSWORD: "pswd"
