apiVersion: apps/v1
kind: Deployment
metadata:
  name: urls-service
  namespace: urls
spec:
  replicas: 1
  selector:
    matchLabels:
      app: urls-service
  template:
    metadata:
      labels:
        app: urls-service
    spec:
      initContainers:
        - name: migrate
          image: ghcr.io/artemborodinevgenyevich/urls-migration:latest
          command: ["goose", "-dir", "/migrations", "postgres",
            "postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(POSTGRES_HOST):$(POSTGRES_PORT)/$(POSTGRES_DB)?sslmode=disable",
            "up"]
          env:
            - name: POSTGRES_HOST
              value: "192.168.57.21"
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USER
              value: "urlshortener"
            - name: POSTGRES_DB
              value: "urlshortener_db"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: urls-service-secrets
                  key: POSTGRES_PASSWORD
      containers:
        - name: urls-service
          image: ghcr.io/artemborodinevgenyevich/urls-service:latest
          ports:
            - containerPort: 9091
          env:
            - name: APP_PORT
              value: "9091"
            - name: APP_ENV
              value: "production"
            - name: POSTGRES_HOST
              value: "192.168.57.21"
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USER
              value: "urlshortener"
            - name: POSTGRES_DB
              value: "urlshortener_db"
            - name: POSTGRES_SSL_MODE
              value: "disable"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: urls-service-secrets
                  key: POSTGRES_PASSWORD
            - name: REDIS_HOST
              value: "192.168.57.21"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_DB
              value: "0"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: urls-service-secrets
                  key: REDIS_PASSWORD
            - name: CACHE_ENABLED
              value: "true"
            - name: CACHE_TTL_MINUTES
              value: "60"
---
apiVersion: v1
kind: Service
metadata:
  name: urls-service
  namespace: urls
spec:
  selector:
    app: urls-service
  ports:
    - port: 9091
