apiVersion: apps/v1
kind: Deployment
metadata:
  name: urls-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: urls-frontend
  template:
    metadata:
      labels:
        app: urls-frontend
    spec:
      containers:
        - name: urls-frontend
          image: urls-frontend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5173
---
apiVersion: v1
kind: Service
metadata:
  name: urls-frontend-service
spec:
  selector:
    app: urls-frontend
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5173
      targetPort: 5173
      nodePort: 30000
